#!/bin/sh

python ~/.local/lib/python2.7/site-packages/speedtest.py > /tmp/speedtest.txt
cp /tmp/speedtest.txt /tmp/ping.txt
cp /tmp/speedtest.txt /tmp/upload.txt


speed=$(cat /tmp/speedtest.txt | sed -n 's/.*Download: \([0-9]\{1,\}\.[0-9]\{2,\}\).*/\1/p')

echo "$speed Mb/s"
